[project]
name = "odoo-addons-oca-account-payment"
version = "19.0.20260630.0"
dependencies = [
    "odoo-addon-account_check_printing_report_base==19.0.*",
    "odoo-addon-account_due_list==19.0.*",
    "odoo-addon-account_due_list_payment_mode==19.0.*",
    "odoo-addon-account_move_line_payment==19.0.*",
    "odoo-addon-account_payment_method_base==19.0.*",
    "odoo-addon-account_payment_notification==19.0.*",
    "odoo-addon-account_payment_return==19.0.*",
    "odoo-addon-account_payment_return_import==19.0.*",
    "odoo-addon-account_payment_term_extension==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
